services:
  db:
    image: postgres:15-alpine
    container_name: crmp_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: crmp_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: crmp_backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:password123@db:5432/crmp_db?schema=public"
      PORT: 3000
      CLOUDINARY_CLOUD_NAME: "${CLOUDINARY_CLOUD_NAME}"
      CLOUDINARY_API_KEY: "${CLOUDINARY_API_KEY}"
      CLOUDINARY_API_SECRET: "${CLOUDINARY_API_SECRET}"
    depends_on:
      - db
    volumes:
      - ./src:/usr/src/app/src
      - ./prisma:/usr/src/app/prisma
    command: npm run dev

volumes:
  pgdata:
